import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Main, Sidebar } from "./components";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="antialiased">
      <body
        className={`${inter.className} h-svh bg-white lg:overflow-hidden dark:bg-zinc-900`}
      >
        <div className="mx-auto h-svh max-w-7xl lg:grid lg:grid-cols-app dark:bg-zinc-900">
          <Sidebar />
          <Main>{children}</Main>
        </div>
      </body>
    </html>
  );
}
